# Generated by Django 4.0.4 on 2022-05-25 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymemo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymemo',
            name='favourite',
            field=models.BooleanField(default=False),
        ),
    ]
